# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(b)
def bfs(adj_list, in_degree, n):
    queue = []
    result = []
    for i in range(1, n + 1):
        if in_degree[i] == 0:
            queue.append(i)
    while queue:
        current = queue.pop(0)
        result.append(current)

        if current in adj_list:
            for j in adj_list[current]:
                in_degree[j] -= 1
                if in_degree[j] == 0:
                    queue.append(j)
    return result
def find_course_order(n, pre):
    adj_list = {}
    in_degree = [0] * (n + 1)
    for i in pre:
        a, b = i
        if a not in adj_list:
            adj_list[a] = []
        adj_list[a].append(b)
        in_degree[b] += 1
    order = bfs(adj_list, in_degree, n)
    if len(order) == n:
        return order
    else:
        return []
file = open("input1b.txt",'r')
n, m = map(int, file.readline().split())
pre= [tuple(map(int, file.readline().split())) for _ in range(m)]
result = find_course_order(n, pre)
o = open("output1b.txt", "w")
if not result:
        o.write("IMPOSSIBLE")
else:
        o.write(" ".join(map(str, result)))
o.close()