# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UQm0TiBpNzY5Ytae4xua0m2NC_3STpXT
"""

network =open("input1a.txt",'r')
output = open("output1a.txt", "w")
def dijkstra(network, start, end):
    distances = {node: float('infinity') for node in network}
    distances[start] = 0
    previous_nodes = {node: None for node in network}
    nodes = set(network)
    while nodes:
        current_node = min(nodes, key=lambda node: distances[node])
        nodes.remove(current_node)
        for neighbor, weight in network[current_node].items():
            potential_distance = distances[current_node] + weight
            if potential_distance < distances[neighbor]:
                distances[neighbor] = potential_distance
                previous_nodes[neighbor] = current_node
    path, current_node = [], end
    while previous_nodes[current_node] is not None:
        path.insert(0, current_node)
        current_node = previous_nodes[current_node]
    path.insert(0, current_node)
    return distances[end], path
distance, route = dijkstra(network, 'Washington', 'Kentucky')
output.write(f"{distance} km")
output.write(" ".join(route))
output.close()

file = open("input1b.txt",'r')
division1 = file.readline()#["Kentucky", "Alabama", "Texas", "Washington", "Florida"]
division2 = file.readline()#["Texas", "Alabama", "Kentucky", "Washington", "Kanas", "Washington", "Delaware", "California", "Florida"]
road_lengths = file.readline()#[80, 50, 50, 50, 85, 100, 75, 60, 125, 75]
o = open("output1b.txt", "w")
def find_meeting_point():
    adam_path = []
    lisa_path = []
    meeting_point = None
    for state1, state2, length in zip(division1, division2, road_lengths):
        adam_path.append(state1)
        lisa_path.append(state2)
        if state1 == state2:
            meeting_point = state1
            break
    o.write(meeting_point)
    o.write(" ".join(adam_path))
    o.write(" ".join(lisa_path))
find_meeting_point()
o.close()