# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#4
def sort_by_weight(data):
	return data[2]

def people_find(vertax, lister):
	for i in range(len(lister)):
		if vertax in lister[i]:
			return i
	return -1

def union(a,b,w, people_friend, totaler):
	ind_a = people_find(a,people_friend)
	ind_b = people_find(b,people_friend)

	if(ind_a != ind_b):
		mini = min(ind_a ,ind_b)
		maxi = max(ind_a ,ind_b)
		people_friend[mini] = people_friend[mini] | people_friend.pop(maxi)
		return totaler+w

file_input= open('input4.txt', 'r')
file_output = open('output4.txt', 'w')
filer=file_input.readlines()

vertax = int(filer[0].split()[0])
total_edge = int(filer[0].split()[1])
connection_map =[]
people_friend =[{i+1} for i in range(vertax)]

for i in range(1, total_edge+1):
	connection_map.append([int(filer[i].split()[0]),int(filer[i].split()[1]),int(filer[i].split()[2])])
connection_map = sorted(connection_map, key=sort_by_weight)

totaler=0

for i in range(len(connection_map)):
	k=union(connection_map[i][0], connection_map[i][1], connection_map[i][2], people_friend, totaler)
	if(type(k) == int):
		totaler=k
file_output.write(f"{totaler}")

file_input.close()
file_output.close()