# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

def DFS(starting_node, graph_list, visited_list, distance):
	q=[k for k in sorted(graph_list[starting_node], key=graph_list[starting_node].get)]

	while q !=[]:
		node = q.pop(0)
		temp_distance = distance[starting_node] + graph_list[starting_node][node]

		if(not visited_list[node] or (visited_list[node] and temp_distance < distance[node])):
			distance[node] = distance[starting_node] + graph_list[starting_node][node]
			visited_list[node] = True
			DFS(node, graph_list, visited_list, distance)

file_input= open('input1.txt', 'r')
file_output = open('output1.txt', 'w')
fil=file_input.readlines()

vertax = int(fil[0].split()[0])
total_edge = int(fil[0].split()[1])
distance =[-1 for i in range(vertax+1)]

visited_list= [False for i in range(vertax+1)]

graph_list = [{} for i in range(vertax+1)]

for i in range(1,total_edge+1):
	a,b, c = int(fil[i].split()[0]),int(fil[i].split()[1]), int(fil[i].split()[2])
	graph_list[a][b] = c

starting_node = int(fil[total_edge+1])
distance[starting_node] = 0
visited_list[starting_node] = True
DFS(starting_node, graph_list, visited_list, distance)

distance.pop(0)

file_output.write(f"{' '.join([str(k) for k in distance])}")


file_input.close()
file_output.close()