# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
def people_find(vertax, lister):
	for i in range(len(lister)):
		if vertax in lister[i]:
			return i
	return -1

def union(a,b,people_friend, file_output):
	ind_a = people_find(a,people_friend)
	ind_b = people_find(b,people_friend)

	if(ind_a != ind_b):
		mini = min(ind_a ,ind_b)
		maxi = max(ind_a ,ind_b)
		people_friend[mini] = people_friend[mini] | people_friend.pop(maxi)
		file_output.write(f"{len(people_friend[mini])}\n")
	else:
		file_output.write(f"{len(people_friend[ind_a])}\n")
file_input= open('input3.txt', 'r')
file_output = open('output3.txt', 'w')
filer=file_input.readlines()

village_people = int(filer[0].split()[0])
query = int(filer[0].split()[1])

people_friend =[{i+1} for i in range(village_people)]

for i in range (1, query+1):
	a,b=int(filer[i].split()[0]), int(filer[i].split()[1])
	union(a,b,people_friend, file_output)
file_input.close()
file_output.close()