# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

# 1
def merge(a, b):
    x=[]
    i = 0
    j = 0
    while i<len(a) and j<len(b):
        if a[i]<b[j]:
            x.append(a[i])
            i+=1
        else:
            x.append(b[j])
            j+=1
    x.extend(a[i:])
    x.extend(b[j:])
    return x

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        a1 = mergeSort(arr[:mid])
        a2 = mergeSort(arr[mid:])
        return merge(a1, a2)
file = open("input1.txt",'r')
text= file.readline()
textx=file.readline()
o = open("output1.txt", "w")
l1=mergeSort(textx)
for i in l1:
  if i!=' ':
    o.write(f'{i} ')
o.close()