# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
def mergeAndCount(arr, temp, left, mid, right):
    i = left
    j = mid + 1
    count = 0
    for k in range(left, right + 1):
        if i > mid:
            temp[k] = arr[j]
            j += 1
        elif j > right:
            temp[k] = arr[i]
            i += 1
        elif arr[i] <= arr[j]:
            temp[k] = arr[i]
            i += 1
        else:
            temp[k] = arr[j]
            j += 1
            count += (mid - i + 1)

    for k in range(left, right + 1):
        arr[k] = temp[k]
    return count
def countInversions(arr, temp, left, right):
    count = 0
    if left < right:
        mid = (left + right) // 2
        count += countInversions(arr, temp, left, mid)
        count += countInversions(arr, temp, mid + 1, right)
        count += mergeAndCount(arr, temp, left, mid, right)
    return count
file = open("input3.txt",'r')
text = int(file.readline())
heights = list(map(int, file.readline().split()))
o = open("output3.txt", "w")
temp = [0] * text
inversions = countInversions(heights, temp, 0, text - 1)
o.write(str(inversions))
o.close()