# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#5
def quickSort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[0]
    left = []
    right = []
    for element in arr[1:]:
        if element <= pivot:
            left.append(element)
        else:
            right.append(element)
    return quickSort(left) + [pivot] + quickSort(right)
file = open("input5.txt",'r')
text = int(file.readline())
arr = list(map(int,file.readline().split()))
o = open("output5.txt", "w")
sorted_arr = quickSort(arr)
for i in sorted_arr:
  o.write(f'{i} ')
o.close()