# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#4
def div(arr,m=0):
    mid=len(arr) // 2
    i=0
    li=[]
    if len(arr)==1:
        return arr,m
    if len(arr)>1 and len(arr)<=2:
        a=arr[0] + pow(arr[1], 2)
        if a>=m:
            m=a
        return arr,m
    l=arr[:mid]
    r=arr[mid:]
    l1,l1_max = div(l,m)
    r1,r1_max = div(r,m)
    if r1_max>=l1_max:
        m=r1_max
    else:
        m=l1_max
    high=max(l1)
    while i<len(r1):
        if m<=high+pow(r1[i],2):
            m=high+pow(r1[i],2)
        i+=1
    li.extend(l1)
    li.extend(r1)
    return li,m
file = open("input4.txt",'r')
o = open("output4.txt",'w')
text = int(file.readline().strip())
arr = list(map(int, (file.readline().split())))
o.write(f'{str(div(arr)[1])}')
o.close()