# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2
def findMax(arr, start, end):
    if start==end:
        return arr[start]
    mid = (start + end) // 2
    lmax = findMax(arr,start,mid)
    rmax = findMax(arr,mid+1,end)
    return max(lmax, rmax)
file = open("input2.txt",'r')
text = int(file.readline())
arr = list(map(int, file.readline().split()))
o = open("output2.txt", "w")
max_value=findMax(arr,0,text-1)
o.write(str(max_value))
o.close()