# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#6
def partition(arr,low,high):
    pivot = arr[low]
    left = low + 1
    right = high
    a= 0
    while not a:
        while left <= right and arr[left] <= pivot:
            left = left + 1
        while arr[right] >= pivot and right >= left:
            right = right - 1
        if right < left:
            a=1
        else:
            arr[left], arr[right] = arr[right], arr[left]
    arr[low], arr[right] = arr[right], arr[low]
    return right
def quick_select(arr, low, high, k):
    if low == high:
        return arr[low]
    pivot_index = partition(arr, low, high)
    if k == pivot_index:
        return arr[k]
    elif k < pivot_index:
        return quick_select(arr, low, pivot_index - 1, k)
    else:
        return quick_select(arr, pivot_index + 1, high, k)
file = open("input6.txt",'r')
text = int(file.readline())
arr = list(map(int,file.readline().split()))
o = open("output6.txt", "w")
q = int(file.readline())
l1=[]
for _ in range(q):
        k = int(file.readline())
        kth_smallest = quick_select(arr, 0, text-1, k-1)
        l1.append(kth_smallest)
for i in range(len(l1)):
        o.write(f'{l1[i]}\n')
o.close()