# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2
def DFS(root, graph_list, visited_list, distance):
	q=[k for k in sorted(graph_list[root], key=graph_list[root].get)]

	while q !=[]:
		node = q.pop(0)
		temp_distance = distance[root] + graph_list[root][node]

		if(not visited_list[node] or (visited_list[node] and temp_distance < distance[node])):
			distance[node] = distance[root] + graph_list[root][node]
			visited_list[node] = True
			DFS(node, graph_list, visited_list, distance)
file_input= open('input2.txt', 'r')
file_output = open('output2.txt', 'w')
filer=file_input.readlines()

vertax = int(filer[0].split()[0])
total_edge = int(filer[0].split()[1])
distance =[-1 for i in range(vertax+1)]

visited_list= [False for i in range(vertax+1)]

graph_list = [{} for i in range(vertax+1)]

for i in range(1,total_edge+1):
	a,b, c = int(filer[i].split()[0]),int(filer[i].split()[1]), int(filer[i].split()[2])
	graph_list[a][b] = c

starting_node, starting_node1  = int(filer[total_edge+1].split()[0]), int(filer[total_edge+1].split()[1])
distance[starting_node] = 0
visited_list[starting_node] = True
DFS(starting_node, graph_list, visited_list, distance)




distance1 =[-1 for i in range(vertax+1)]
visited_list1= [False for i in range(vertax+1)]
distance1[starting_node1] = 0
visited_list1[starting_node1] = True

DFS(starting_node1, graph_list, visited_list1, distance1)


node=0
timer = 0
for i in range(1, vertax+1):

	if(distance[i] >0 and distance1[i] > 0):

		check_dif = distance[i] -distance1[i]
		if (check_dif <0):
			check_dif *= -1
		if(node == 0):
			node = i
			timer = max(distance[i], distance1[i])
		else:
			base_diff= distance[node] -distance1[node]
			if(base_diff <0):
				base_diff *= -1
			if(check_dif < base_diff):
				node=i
				timer = max(distance[i], distance1[i])
			elif(check_dif == base_diff):
				base=distance[node] +distance1[node]
				check=distance[i] +distance1[i]
				if(max(base,check) == base):
					node=i
					timer = max(distance[i], distance1[i])


if(node == 0):
	file_output.write(f"Impossible")
else:
	file_output.write(f"Time: {timer}\nNode: {node}")

file_input.close()
file_output.close()