# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#4
file= open('input4.txt','r')
a= file.readline()
x = open("output4.txt", "w")
n=[]
t=[]
f=[]
for i in range(int(a)):
  z=file.readline()
  f.append(z)
  n.append(z.split()[0])
  t.append(z.split()[-1])
for i in range(len(z)):
  o=0
  for j in range(len(n)-i-1):
    if n[j]>n[j+1]:
            n[j],n[j+1]=n[j+1],n[j]
            f[j],f[j+1]=f[j+1],f[j]
            o=1
    if n[j]==n[j+1] and t[j]>t[j+1]:
            t[j], t[j+1]=t[j+1],t[j]
            f[j],f[j+1]=f[j+1],f[j]
            o=1
    if n[j]==n[j+1] and t[j]==t[j+1]:
      f[j]=f[j]
  if o==0:
    break
for i in f:
    x.write(f'{i}\n')
x.close()