# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
file= open('input3.txt','r')
a= file.readline()
x = open("output3.txt", "w")
k=list(map(int, file.readline().split()))
v=list(map(int, file.readline().split()))
d=[]
for i in range(int(a)):
    std = {"id": k[i], "mar": v[i]}
    d.append(std)
for i in range(int(a)-1):
    f = 0
    for j in range(int(a)-1-i):
        if d[j]["mar"]<d[j+1]["mar"] or (d[j]["mar"]==d[j+1]["mar"] and d[j]["id"]>d[j+1]["id"]):
            d[j],d[j+1]=d[j+1],d[j]
            f=1
    if f==0:
        break
for std in d:
    x.write(f'ID: {std["id"]} Mark: {std["mar"]}\n')
x.close()