# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2(a)
def merge(a,b):
    arr=[0]*(len(a)+len(b))
    i=0
    j=0
    k=0
    while i<len(a) and j<len(b):
      if a[i]<b[j]:
        arr[k]=a[i]
        i+=1
      else:
        arr[k]=b[j]
        j+=1
      k+=1
    while i<len(a):
      arr[k]=a[i]
      i+=1
      k+=1
    while j<len(b):
      arr[k]=b[j]
      j+=1
      k+=1
    for z in arr:
      x.write(f'{z} ')
    x.close()
file = open("input2a.txt",'r')
text= file.readline()
textx=file.readline()
textxx=file.readline()
textxxx=file.readline()
x=open("output2a.txt","w")
a=list(map(int,textx.split()))
b=list(map(int,textxxx.split()))
merge(a,b)