# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
file = open("input3.txt",'r')
text= file.readline()
x=open("output3.txt","w")
tas=[]
for _ in range(int(text)):
    a,b = map(int,file.readline().split())
    tas.append((a,b))
tas.sort(key=lambda x:x[1])
c_tas=[]
c_end=-1
for i in tas:
    a,b =i
    if a>= c_end:
        c_tas.append(i)
        c_end=b
x.write(f'{len(c_tas)}\n')
for j in c_tas:
    x.write(f'{j[0]},{j[1]}\n')
x.close()