# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#4
file = open("input4.txt",'r')
text= file.readline()
x=open("output4.txt","w")
n,m=map(int,text.split())
tas=[]
for i in range(n):
    a,b=map(int,file.readline().split())
    tas.append((a,b))
tas.sort(key=lambda x:x[1])
c_tas = 0
e_t = [0]*m# Number to take suppose N,M means 2 number
for i in tas:
    a,b=i
    for i in range(m):
        if a>= e_t[i]:
            e_t[i]=b
            c_tas+=1
            break
x.write(f'{c_tas}')
x.close()