# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2(b)
file = open("input2b.txt",'r')
text= file.readline()
textx=file.readline()
textxx=file.readline()
textxxx=file.readline()
x=open("output2b.txt","w")
a=list(map(int,textx.split()))
b=list(map(int,textxxx.split()))
arr=[]
i=0
j=0
while i<len(a) and j<len(b):
  if a[i]<b[j]:
    arr.append(a[i])
    i+=1
  else:
    arr.append(b[j])
    j+=1
arr.extend(a[i:])
arr.extend(b[j:])
for z in arr:
  x.write(f'{z} ')
x.close()