# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(b)
file = open("input1b.txt",'r')
text= file.readline()
textx=file.readline()
x=open("output1b.txt","w")
n,s=map(int,text.split())
arr=list(map(int,textx.split()))
dic={}
for i in range(n):
    cval=arr[i]
    nval=s-cval
    if nval in dic:
        x.write(f'{dic[nval]+1},{i + 1}')
        break
    dic[cval]=i
else:
    x.write("IMPOSSIBLE")
x.close()