# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2
def dfs(ver, adj_list, v_list, c, t):
    q=adj_list[ver]
    updated=c
    while q != []:
        new = q.pop(0)
        if(new not in v_list):
            v_list.append(new)
            t[new].append(c)
            updated += 1
            updated=dfs(new, adj_list, v_list, updated, t)
            t[new].append(updated)
            updated+=1
    return updated
file_input= open('input2.txt', 'r')
file_output = open('output2.txt', 'w')
filer=file_input.readlines()
vertax = int(filer[0].split()[0])
total_edge = int(filer[0].split()[1])
adj_list = [[] for i in range(vertax+1)]
reverse_list = [[] for i in range(vertax+1)]
visited_list = []
timer = [[] for i in range(vertax+1)]
n=0
for i in range(1,total_edge+1):
    a,b = int(filer[i].split()[0]),int(filer[i].split()[1])
    adj_list[a].append(b)
    reverse_list[b].append(a)
pre=[]
for i in range(1,vertax+1):
    if(reverse_list[i] == []):
        pre.append(i)
pre= sorted(pre,reverse=True)
for i in pre:
    if(i not in visited_list):
        visited_list.append(i)
        timer[i].append(n)
        n+=1
        n=dfs(i, adj_list, visited_list, n, timer)
        timer[i].append(n)
        n+=1
if(len(visited_list) != vertax):
    file_output.write(f"Impossible")
else:
    b={}
    for i in range(1,len(timer)):
        b[timer[i][1]]=i
    file_output.write(f"{' '.join([str(b[i]) for i in sorted(list(b.keys()),reverse=True)])}")
file_output.close()