# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(a)
def dfs(ver, adj_list, v_list, counter, t):
    q=adj_list[ver]
    counter_up=counter
    while q != []:
        new = q.pop(0)
        if(new not in v_list):
            v_list.append(new)
            t[new].append(counter)
            counter_up += 1
            counter_up=dfs(new, adj_list, v_list, counter_up, t)
            t[new].append(counter_up)
            counter_up+=1
    return counter_up

file_input= open('input1a.txt', 'r')
file_output = open('output1a.txt', 'w')
filer=file_input.readlines()

ver = int(filer[0].split()[0])
edge = int(filer[0].split()[1])

adj_list = [[] for i in range(ver+1)]
reverse_list = [[] for i in range(ver+1)]
visited_list = []
timer = [[] for i in range(ver+1)]
counter=0

for i in range(1,edge+1):
    a,b = int(filer[i].split()[0]),int(filer[i].split()[1])
    adj_list[a].append(b)
    reverse_list[b].append(a)

pre=[]
for i in range(1,ver+1):
    if(reverse_list[i] == []):
        pre.append(i)


for i in pre:
    if(i not in visited_list):
        visited_list.append(i)
        timer[i].append(counter)
        counter+=1
        counter=dfs(i, adj_list, visited_list, counter, timer)
        timer[i].append(counter)
        counter+=1

if(len(visited_list) != ver):
    file_output.write(f"Impossible")
else:
    b={}
    for i in range(1,len(timer)):
        b[timer[i][1]]=i
    file_output.write(f"{' '.join([str(b[i]) for i in sorted(list(b.keys()),reverse=True)])}")
file_output.close()