# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
def initialize(g,n):
    for i in range(n):
        g.append([])
        visited.append(0)

def addE(g,a,b):
    g[a].append(b)
    g[b].append(a)

def dfs(graph,a):
    visited[a]=1
    path.append(a+1)
    for i in g[a]:
        if not visited[i]:
            dfs(g,i)
file = open("input3.txt",'r')
o = open("output3.txt", "w")
n,m=map(int, file.readline().split())
g=[]
visited=[]
initialize(g,n)
for _ in range(m):
    a,b= map(int, file.readline().split())
    addE(g,a,b)
path=[]
dfs(g,0)
o.write(' '.join(map(str, path)))
o.close()