# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(a)
file= open('input1a.txt','r')
text= file.readline()
f = open("output1a.txt", "w")
for i in range(int(text)):
  a=file.readline()
  if int(a)%2==0:
    n='an Even'
  else:
    n='a Odd'
  f.write(f'{int(a)} is {n} number.\n')
f.close()