# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(b)
file= open('input1b.txt','r')
text= file.readline()
f = open("output1b.txt", "w")
for i in range(int(text)):
  a=file.readline()
  p=a.split()
  z=int(p[1])
  r=int(p[3])
  if p[2]=='+':
    q=z+r
    f.write(f'The result of {z}+{r} is {q}\n')
  if p[2]=='-':
    q=z-r
    f.write(f'The result of {z}-{r} is {q}\n')
  if p[2]=='*':
    q=z*r
    f.write(f'The result of {z}*{r} is {q}\n')
  if p[2]=='/':
    q=z/r
    f.write(f'The result of {z}/{r} is {q}\n')
f.close()