# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#2
file= open('input2.txt','r')
a= file.readline()
x = open("output2.txt", "w")
arr=list(map(int, file.readline().split()))
def bubbleSort(arr):
  for i in range(len(arr)-1):
    f=0
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        f=1
    if f==0:
        break
  return arr
for i in (bubbleSort(arr)):
      x.write(f'{i} ')
x.close()