# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#3
def dfs(p_vertex, vertex, adj_list, visited_l1, temp_visited):
    q=[]
    if(p_vertex in adj_list[vertex]):
        return [vertex]

    for i in adj_list[vertex]:
        if(i not in temp_visited and i not in visited_l1):
            q.append(i)
    temp_visited.append(vertex)

    while q!=[]:
        attempt=q.pop(0)
        action=dfs(p_vertex, attempt, adj_list, visited_l1, temp_visited)
        if(action != False):
            return [attempt]+action
    return False

file_input= open('input3.txt', 'r')
file_output = open('output3.txt', 'w')
fn=file_input.readlines()
ver = int(fn[0].split()[0])
edge = int(fn[0].split()[1])
adj_list = [[] for i in range(ver+1)]
visited_list = []
fin=[]
for i in range(1,edge+1):
    a,b = int(fn[i].split()[0]),int(fn[i].split()[1])
    adj_list[a].append(b)
for i in range(1, ver+1):
    if(i not in visited_list):
        temp_visited_list=[]
        r=dfs(i, i,adj_list, visited_list, temp_visited_list)
        if(r== False):
            fin.append([i])
        else:
            fin.append([i]+r[:-1])
            visited_list+=r
for i in range(len(fin)):
    file_output.write(f'{fin[i]}\n')
file_output.close()