# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1b
file_input= open('input1b.txt', 'r')
file_output = open('output1b.txt', 'w')
f=file_input.readlines()

ver = int(f[0].split()[0])
edge = int(f[0].split()[1])

adj_list = [[] for i in range(ver+1)]
rev = [[] for i in range(ver+1)]
visited = [0]
q =[]

for i in range(1,edge+1):
    a,b = int(f[i].split()[0]),int(f[i].split()[1])
    adj_list[a].append(b)
    rev[b].append(a)

in_deg = [len(i) for i in rev]

for i in range(ver+1):
    for i in range(len(in_deg)):
        if(i not in visited and in_deg[i] == 0 and i not in q):
            q.append(i)
    if(q != []):
        attempt = q.pop(0)
        for i in adj_list[attempt]:
            if(i not in visited):
                in_deg[i] -=1
        visited.append(attempt)


if (len(visited[1:]) != ver):
    file_output.write(f"IMPOSSIBLE")
else:
    file_output.write(f"{ ' '.join([str(i) for i in visited[1:]]) }")
file_output.close()