# -*- coding: utf-8 -*-
"""22101008_Sadman_Rahman_CSE422_01_Assignment01_Fall2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa2ME0PS6Km5lWI7Fm7LGSFb9W0WeT7b
"""

import heapq
def graph_a(input):
    g = {}
    h = {}
    f = open(input, 'r')
    for i in f:
        p = i.split()
        n = p[0]
        h1 = int(p[1])
        h[n] = h1
        neighbors = {}
        for j in range(2, len(p), 2):
            neighbor = p[j]
            d = int(p[j + 1])
            neighbors[neighbor] = d
        g[n] = neighbors
    f.close()
    return g, h
def a_star_search(g, h, start, end):
    fringe = []
    heapq.heappush(fringe, (0 + h[start], start, 0, [start]))
    vx = set()
    while fringe:
        f_cost, c_n, c_cost, path = heapq.heappop(fringe)
        if c_n in vx:
            continue
        if c_n == end:
            return path, c_cost
        vx.add(c_n)
        neighbors = g[c_n]
        for neighbor in neighbors:
            if neighbor not in vx:
                d = neighbors[neighbor]
                n_cost = c_cost + d
                e_cost = n_cost + h[neighbor]
                heapq.heappush(fringe, (e_cost, neighbor, n_cost, path + [neighbor]))
    return None, None
input = 'Input file.txt'
g, h = graph_a(input)
start_node = 'Arad'
destination = 'Bucharest'
path, total_d = a_star_search(g, h, start_node, destination)
output_file = open('output.txt', 'w')
if path:
    output_file.write(f"Path: {' -> '.join(path)}\n")
    output_file.write(f"Total distance: {total_d} km")
else:
    output_file.write("NO PATH FOUND")
output_file.close()