# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DgS8jEgEqlCz_0Gm8MP1cZBQg-O6cyF
"""

#1(a)
file = open("input1a.txt",'r')
text= file.readline()
textx=file.readline()
x = open("output1a.txt", "w")
n,z = map(int, text.split())
arr = list(map(int, textx.split()))
r="IMPOSSIBLE"
for i in range(n):
    for j in range(i+1,n):
        if arr[i]+arr[j]==z:
            result = f"{i+1} {j+1}"
            break
    if r!="IMPOSSIBLE":
        break
x.write(r)
x.close()